//API ---> APPLICATION PROGRAMING INTERFACE


// web  application 
//FRONT END  --> WEBSITE ( DESGIN , BUTTON , JS )
// BACKEND  --> (THE ACTION THAT YOU GET AFTER GIVEING REACTION TO WEB PAGE ) ---> API 
// SERVER  --> DATA STORE PLACES 

// TECHINACAL ROLES 

//1 FRONT END DEVEOPLER  --> HTML , CSS, JS ,
//2 BACKEND DEVELOPER  --> 
//3 DBA --> DATAABSE BASE ADMINSTOR --> 
//4 DEVEOPS ENGINNER --> 
// 5 TESTOR -->
// MANNUAL TESTOR
//API TESTOR 
// ETL 
// AUTOMATION

// FULL STACK DEVEOPLER  -- FORNT END , BACKEND , DBA ,(DEVEOPS)
// FULL STACK TESTOR --> AUTAOMATION , ETL TESTOR , PERFORMANCE , API , MANNUAL 

// API IS THE COMMUICATION LINK BETWEEN FRONT END AND THE SERVER 

//SOAP-->(THIS IS A OLDER SERVICE) --->XML --> 
//REST-->( THIS IS NEW GEN SERIVECE ) --> JSON (99 %)

// SOAP SERVIVES ARE TESTED ON TOOL LIKE --> SOAP UI 
// REST SERVICES ARE TESTED ON TOOLS LIKE --> POSTMAN , SWAAGER 


// REST SERVICES -->

//GET --> IT GETS AALL THE INFORMATION --> 
//POST -->CREATE IT NEW INFORMATION --> 
//PUT --> UPDATE THE CREATED DATA 
//UPDATE -->  UPDATE THE CREATED DATA 
//PATCH --> UPDATE THE CREATED DATA 
//DELETE --> DELETE ALL THE DATA 


// IF YOU HAVE  A SINGLE API TO TEST --> API REQUEST 
// IF YOU HAVE  A MULTIPLE API TO TEST --> COLLECTION   